# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc/Zybo-Z7-Master.xdc

# Block Designs: bd/aes7/aes7.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes7 || ORIG_REF_NAME==aes7} -quiet] -quiet

# IP: bd/aes7/ip/aes7_processing_system7_0_0/aes7_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes7_processing_system7_0_0 || ORIG_REF_NAME==aes7_processing_system7_0_0} -quiet] -quiet

# IP: bd/aes7/ip/aes7_axi_bram_ctrl_0_0/aes7_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes7_axi_bram_ctrl_0_0 || ORIG_REF_NAME==aes7_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/aes7/ip/aes7_axi_smc_0/aes7_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes7_axi_smc_0 || ORIG_REF_NAME==aes7_axi_smc_0} -quiet] -quiet

# IP: bd/aes7/ip/aes7_rst_ps7_0_50M_0/aes7_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes7_rst_ps7_0_50M_0 || ORIG_REF_NAME==aes7_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/aes7/ip/aes7_setpointgenerator_0_0/aes7_setpointgenerator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes7_setpointgenerator_0_0 || ORIG_REF_NAME==aes7_setpointgenerator_0_0} -quiet] -quiet

# IP: bd/aes7/ip/aes7_blk_mem_gen_1_0/aes7_blk_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes7_blk_mem_gen_1_0 || ORIG_REF_NAME==aes7_blk_mem_gen_1_0} -quiet] -quiet

# XDC: bd/aes7/aes7_ooc.xdc
