# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc/Zybo-Z7-Master.xdc

# Block Designs: bd/aes7/aes7.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes7 || ORIG_REF_NAME==aes7} -quiet] -quiet

# IP: bd/aes7/ip/aes7_processing_system7_0_0/aes7_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes7_processing_system7_0_0 || ORIG_REF_NAME==aes7_processing_system7_0_0} -quiet] -quiet

# IP: bd/aes7/ip/aes7_rst_ps7_0_50M_2/aes7_rst_ps7_0_50M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes7_rst_ps7_0_50M_2 || ORIG_REF_NAME==aes7_rst_ps7_0_50M_2} -quiet] -quiet

# IP: bd/aes7/ip/aes7_axi_gpio_0_0/aes7_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes7_axi_gpio_0_0 || ORIG_REF_NAME==aes7_axi_gpio_0_0} -quiet] -quiet

# IP: bd/aes7/ip/aes7_ps7_0_axi_periph_1/aes7_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes7_ps7_0_axi_periph_1 || ORIG_REF_NAME==aes7_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/aes7/ip/aes7_quaddecoder_0_0/aes7_quaddecoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes7_quaddecoder_0_0 || ORIG_REF_NAME==aes7_quaddecoder_0_0} -quiet] -quiet

# IP: bd/aes7/ip/aes7_pscommunicator_0_0/aes7_pscommunicator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes7_pscommunicator_0_0 || ORIG_REF_NAME==aes7_pscommunicator_0_0} -quiet] -quiet

# IP: bd/aes7/ip/aes7_pwm_0_0/aes7_pwm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes7_pwm_0_0 || ORIG_REF_NAME==aes7_pwm_0_0} -quiet] -quiet

# IP: bd/aes7/ip/aes7_PID_CONTROLLER_0_0/aes7_PID_CONTROLLER_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes7_PID_CONTROLLER_0_0 || ORIG_REF_NAME==aes7_PID_CONTROLLER_0_0} -quiet] -quiet

# IP: bd/aes7/ip/aes7_clk_dev_0_0/aes7_clk_dev_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes7_clk_dev_0_0 || ORIG_REF_NAME==aes7_clk_dev_0_0} -quiet] -quiet

# IP: bd/aes7/ip/aes7_auto_pc_0/aes7_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aes7_auto_pc_0 || ORIG_REF_NAME==aes7_auto_pc_0} -quiet] -quiet

# XDC: bd/aes7/aes7_ooc.xdc
