# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/psf/Home/vivado/aes7/aes7.srcs/sources_1/bd/aes7/ip/aes7_processing_system7_0_0/aes7_processing_system7_0_0.xci
# IP: The module: 'aes7_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/psf/Home/vivado/aes7/aes7.srcs/sources_1/bd/aes7/ip/aes7_processing_system7_0_0/aes7_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'aes7_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /media/psf/Home/vivado/aes7/aes7.srcs/sources_1/bd/aes7/ip/aes7_processing_system7_0_0/aes7_processing_system7_0_0.xci
# IP: The module: 'aes7_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/psf/Home/vivado/aes7/aes7.srcs/sources_1/bd/aes7/ip/aes7_processing_system7_0_0/aes7_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'aes7_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
