# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/parallels/vivado/aes7/aes7.srcs/sources_1/bd/aes7/ip/aes7_auto_pc_0/aes7_auto_pc_0.xci
# IP: The module: 'aes7_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/parallels/vivado/aes7/aes7.srcs/sources_1/bd/aes7/ip/aes7_auto_pc_0/aes7_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'aes7_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/parallels/vivado/aes7/aes7.srcs/sources_1/bd/aes7/ip/aes7_auto_pc_0/aes7_auto_pc_0.xci
# IP: The module: 'aes7_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/parallels/vivado/aes7/aes7.srcs/sources_1/bd/aes7/ip/aes7_auto_pc_0/aes7_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'aes7_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
